powerux-jquery-selectablelist/config/routes.rb
PoweruxJquerySelectablelist::Application.routes.draw do
  
  root :to => 'teams#index'
  
  resources :teams do
    get 'locate', :on => :collection 
    get 'select', :on => :collection
    post 'selected', :on => :collection
  end

  resources :players do
    get 'select', :on => :collection
    get 'autocomplete_team_name', :on => :collection
    get 'autocomplete_player_given_name', :on => :collection
  end

end

powerux-jquery-selectablelist/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  
  validates_presence_of :sur_name, :on => :save
  validates_presence_of :given_name, :on => :save
  validates_presence_of :team_abbreviation, :on => :save
  
  def full_name
    "#{given_name} #{sur_name}"
  end
  
  def team_name
    team.name if team
  end
  
  def team_name=(name)
    self.team = Team.find_by_name(name) unless name.blank?
  end
end

powerux-jquery-selectablelist/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
  
  def self.locate()
    select('name, latitude, longitude').all
  end
end

powerux-jquery-selectablelist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

powerux-jquery-selectablelist/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  # TODO: Add select display action 
  def select
  end

  # GET /players
  # GET /players.xml
  def index
    @players = Player.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @players }
    end
  end

  # GET /players/1
  # GET /players/1.xml
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @player }
    end
  end

  # GET /players/new
  # GET /players/new.xml
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.xml
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to(@player, :notice => 'Player was successfully created.') }
        format.xml  { render :xml => @player, :status => :created, :location => @player }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.xml
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to(@player, :notice => 'Player was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @player.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.xml
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to(players_url) }
      format.xml  { head :ok }
    end
  end

  autocomplete :team, :name
  autocomplete :player, :given_name, :display_value => :full_name
end

powerux-jquery-selectablelist/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    layout 'application', :except => :locate

    def locate
      @map = GMap.new("map_div")
      @map.control_init(:large_map => true,:map_type => true)
      add_team_markers(@map, Team.locate)
    end
    
    # TODO: Add select display action 
    def select
      @teams = Team.all
    end

    def selected
      flash[:notice] = params.inspect
      redirect_to :action => 'index'
    end

  # GET /teams
  # GET /teams.xml
  def index
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.xml
  def show
    @team = Team.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.xml
  def new
    @team = Team.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @team }
    end
  end

  # GET /teams/1/edit
  def edit
    @team = Team.find(params[:id])
  end

  # POST /teams
  # POST /teams.xml
  def create
    @team = Team.new(params[:team])

    respond_to do |format|
      if @team.save
        format.html { redirect_to(@team, :notice => 'Team was successfully created.') }
        format.xml  { render :xml => @team, :status => :created, :location => @team }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @team.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.xml
  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to(@team, :notice => 'Team was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @team.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.xml
  def destroy
    @team = Team.find(params[:id])
    @team.destroy

    respond_to do |format|
      format.html { redirect_to(teams_url) }
      format.xml  { head :ok }
    end
  end
  
private
  def add_team_markers( map, teams = [] )
    teams.each do |team|
      map.overlay_init(GMarker.new([team.latitude,team.longitude],:title => team.name,:info_window => team.name))
    end
    map.center_zoom_init([41.508577,-96.240234],4)
  end
end

powerux-jquery-selectablelist/app/helpers/application_helper.rb
module ApplicationHelper
end

powerux-jquery-selectablelist/app/helpers/players_helper.rb
module PlayersHelper
end

powerux-jquery-selectablelist/app/helpers/teams_helper.rb
module TeamsHelper
end

powerux-jquery-selectablelist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Powerux JQuery Selectable List</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.2.min.js', 'jquery-ui-1.8.5.custom.min.js', 'powerux-jquery-selectablelist.js', 'autocomplete-rails.js' %>
  <%= csrf_meta_tag %>
</head>
<body>
	<nav>
		<ul>
			<li><%= link_to "Teams", teams_path %> </li>
			<li><%= link_to "Players", players_path %> </li>
			<li><%= link_to "Team Select", select_teams_path %> </li>
			<li><%= link_to "Player Select", select_players_path %> </li>
		</ul>
	</nav>

<%= yield %>

</body>
</html>

powerux-jquery-selectablelist/app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sur_name %><br />
    <%= f.text_field :sur_name %>
  </div>
  <div class="field">
    <%= f.label :given_name %><br />
    <%= f.text_field :given_name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
	<%= f.label :team_name %><br />
	<%= f.text_field :team_name, :limit => 50, :autocomplete => autocomplete_team_name_players_path %>
  </div>
  <div class="field">
    <%= f.label :team_abbreviation %><br />
    <%= f.text_field :team_abbreviation %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br />
    <%= f.date_select :birth_date %>
  </div>
  <div class="field">
    <%= f.label :place_of_birth %><br />
    <%= f.text_field :place_of_birth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

powerux-jquery-selectablelist/app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

powerux-jquery-selectablelist/app/views/players/index.html.erb
<h1>Listing players</h1>

<table>
  <tr>
    <th>Sur name</th>
    <th>Given name</th>
    <th>Position</th>
    <th>Team abbreviation</th>
    <th>Birth date</th>
    <th>Place of birth</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @players.each do |player| %>
  <tr>
    <td><%= player.sur_name %></td>
    <td><%= player.given_name %></td>
    <td><%= player.position %></td>
    <td><%= player.team_abbreviation %></td>
    <td><%= player.birth_date %></td>
    <td><%= player.place_of_birth %></td>
    <td><%= link_to 'Show', player %></td>
    <td><%= link_to 'Edit', edit_player_path(player) %></td>
    <td><%= link_to 'Destroy', player, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Player', new_player_path %>

powerux-jquery-selectablelist/app/views/players/new.html.erb
<h1>New player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

powerux-jquery-selectablelist/app/views/players/select.html.erb
<p id="notice"><%= notice %></p>
<h2>Player Select</h2>
<div class="selectablelist">
	<%= text_field_tag 'match', 'Enter match text', :class => 'selectabletext'  %>
	<%= select_tag( :my_players, nil, :multiple => true, :size => 6, :class => 'selectablelistleft' ) %>
	<%= select_tag( :my_selected_players, nil, :multiple => true, :size => 6, :class => 'selectablelistright' ) %>
	<div class='selectablelistbuttons'>
		<%= submit_tag 'Add', :name => 'left2right' %> <br />
		<%= submit_tag 'Add All', :name => 'left2right', :class => 'all' %> <br />
		<%= submit_tag 'Remove', :name => 'right2left' %> <br />
		<%= submit_tag 'Remove All', :name => 'right2left', :class => 'all' %> 
	</div>
	<%= hidden_field_tag "selectable_list_ids[]", nil, :class => 'selectablelist_ids' %>
</div>

powerux-jquery-selectablelist/app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sur name:</b>
  <%= @player.sur_name %>
</p>

<p>
  <b>Given name:</b>
  <%= @player.given_name %>
</p>

<p>
  <b>Position:</b>
  <%= @player.position %>
</p>

<p>
  <b>Team abbreviation:</b>
  <%= @player.team_abbreviation %>
</p>

<p>
  <b>Birth date:</b>
  <%= @player.birth_date %>
</p>

<p>
  <b>Place of birth:</b>
  <%= @player.place_of_birth %>
</p>


<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>